# Generated by Django 3.0.3 on 2020-02-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('filed_by', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('nw', 'New'), ('nprgs', 'In Progress'), ('dn', 'Done'), ('nvld', 'Invalid')], default='nw', max_length=5)),
                ('assigned_to', models.CharField(max_length=20)),
                ('completed_by', models.CharField(max_length=20)),
            ],
        ),
    ]
